
RESDIR := $(SRCDIR)/res/overworld


CLEANTARGETS := $(CLEANTARGETS) $(RESDIR)/overworld.chr $(RESDIR)/overworld.chr.pb16

INITTARGETS := $(INITTARGETS) $(RESDIR)/overworld.chr $(RESDIR)/overworld.chr.pb16

$(RESDIR)/overworld.chr: $(RESDIR)/sprite.png
	rgbgfx -h -o $@ $<
